# @file
# .travis.yml - PKP Plugins Integration

dist: focal
os: linux
language: php

addons:
  chrome: beta
  postgresql: "9.5"
  apt:
    update: true
    packages:
      - libvulkan1
      - libu2f-udev

sudo: required

php:
  - 8.0
  - 8.1.0

env:
  - APPLICATION=ojs BRANCH=stable-3_4_0 TEST=mysql
  - APPLICATION=ojs BRANCH=stable-3_4_0 TEST=pgsql
  - APPLICATION=omp BRANCH=stable-3_4_0 TEST=mysql
  - APPLICATION=omp BRANCH=stable-3_4_0 TEST=pgsql
  - APPLICATION=ops BRANCH=stable-3_4_0 TEST=mysql
  - APPLICATION=ops BRANCH=stable-3_4_0 TEST=pgsql

install:
  # Prepare OJS/OMP/OPS environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install --silent && npm run build
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/customLocale

script:
  - $(npm bin)/cypress run --headless --browser chrome --config '{"specPattern":["cypress/tests/data/10-ApplicationSetup/{10-Installation,20-CreateContext}.cy.js","plugins/generic/customLocale/cypress/tests/functional/*.cy.{js,jsx,ts,tsx}"]}'

after_failure:
  - cat error.log
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout

