# @file
# .travis.yml - PKP Plugins Integration

dist: bionic
os: linux
language: php

addons:
  postgresql: "9.5"
  apt:
    update: true

sudo: required

php:
  - 8.0
  - 8.1.0

env:
  - APPLICATION=ojs BRANCH=main TEST=mysql
  - APPLICATION=ojs BRANCH=main TEST=pgsql
  - APPLICATION=omp BRANCH=main TEST=mysql
  - APPLICATION=omp BRANCH=main TEST=pgsql
  - APPLICATION=ops BRANCH=main TEST=mysql
  - APPLICATION=ops BRANCH=main TEST=pgsql

install:
  # Prepare OJS/OMP/OPS environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install --silent && npm run build
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/customLocale

script:
  - $(npm bin)/cypress run --headless --browser chrome --config '{"specPattern":["cypress/tests/data/10-Installation.cy.js","cypress/tests/data/20-CreateContext.cy.js","plugins/generic/customLocale/cypress/tests/**/*.cy.{js,jsx,ts,tsx}"]}'

after_failure:
  - cat error.log
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout

