# @file
# .travis.yml - PKP Plugins Integration

language: php

addons:
  apt:
    update: true

sudo: required

php:
  - 7.3
  - 7.4
env:
  - APPLICATION=ojs BRANCH=main TEST=mysql
  - APPLICATION=ojs BRANCH=main TEST=pgsql
  - APPLICATION=omp BRANCH=main TEST=mysql
  - APPLICATION=omp BRANCH=main TEST=pgsql

install:
  # Prepare OJS/OMP/OPS environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install --silent && npm run build
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/generic/customLocale
  # Install OJS/OMP/OPS & prep data environment
  - $(npm bin)/cypress run --spec "cypress/tests/data/10-Installation.spec.js,cypress/tests/data/20-CreateContext.spec.js"

script:
  - $(npm bin)/cypress run --config integrationFolder=plugins/generic/customLocale/cypress/tests

after_failure:
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout

